### ISSUE TITLE
vocab file for finetuning

### ISSUE THREAD

**Issue by dangvansam98** [cywang97/unispeech#2]
your implemention is very well! i have some questions. 
how i can to create vocab file for my dataset? because i didn't found the script to create vocab file in your repo. and i have pretrained BPE sentencepiece model so i want to use vocab from that for run finetuning and how to do that!
thank for your help!

**Comment by dangvansam98** [comment]
@cywang97 finetune for orther language with difference vocab file (!= pretrained vocab, eg: in English) (so the shape of final layer (for CTC) is change too). how can i run finetuning with pretrained model with orther vocab file. thanks

**Comment by cywang97** [comment]
Hi, during finetuning, you need to remove the pre-trained CTC layer and use a new layer for the target vocabulary. You can create a new vocab file with the same format as the pre-training one.

**Comment by dangvansam98** [comment]
oh. it really means a lot to me. thank you for your help!

Vào Th 3, 7 thg 9, 2021 vào lúc 18:07 Chengyi Wang <
***@***.***> đã viết:
